import { GoogleLogin } from '@react-oauth/google';
import { useAuth } from '../utils/AuthContext'



const LoginPage = () => {

    const { login } = useAuth()

    return (
      <div className="login-page">
        <h1>Travel AI</h1>
        <p className='app-tagline'>Explore world, with best intenory generated by AI</p>
        <GoogleLogin
          onSuccess={(respose) => {
            const token = respose.credential;
            if (token) {
                login(token)
            } else {
              console.error("empty token");
            }
          }}
          onError={() => {
            console.log("Login Failed");
          }}
        />
      </div>
    );
  };
  
  export { LoginPage };
  